# VICTOR
## Data analyst student

# INTRODUCTION TO PYTHON
## This is my first script

In [1]:
print("hello world")

hello world

In [2]:
1+1

2

In [3]:
print( 5+10)

15

# python data types

# 1 INTEGER

In [4]:
X =20 #integer  
X

20

# 2.FLOAT

In [5]:
Y= 3.14   # float
print(Y)

3.14

# 3.STRING; REPRESENT SEQUENCE OF CHARACTERS

In [6]:
name='victor munene' # string
print (name)

victor munene

In [258]:
greeting ='hello'
print (greeting)

hello

# 4.Boolean;Represents true or false values

In [8]:
is_valid = True    #Boolean
is_valid

True

In [9]:
is_valid = False   #Boolean
is_valid

False

In [10]:
is_valid = True  #Boolean
print (is_valid)

True

# 5.LIST;An Ordered ,mutable collection of items

In [11]:
fruits = ["apple","banana","orange" ]
print (fruits)

['apple', 'banana', 'orange']

In [12]:
fruits = ["apple","banana","orange"]
print (fruits[0]) # Access first element
print (fruits[1]) # Access second element
print (fruits[2]) # Access third element

apple
banana
orange

# 6.TUPLE :An ordered,immutable collection of items

In [260]:
my_tuple = (1,2,3,"John" , True)
my_tuple

(1, 2, 3, 'John', True)

# 7.SET:An unordered mutable collection of unique items

In [262]:
my_set = (1,2,3,"john")
print (my_set)

(1, 2, 3, 'john')

# 8.DICTIONARY:A collection of key value pairs

In [15]:
my_dict = {
    "Name" : "John",
    "age" : "20",
    "gender" : "male",
    "occupation" : "data analyst"}
my_dict

{'Name': 'John', 'age': '20', 'gender': 'male', 'occupation': 'data analyst'}

In [16]:
person ={
    "name" :"victor munene",
    "age" : "19",
"occupation" : "teacher"}
person

{'name': 'victor munene', 'age': '19', 'occupation': 'teacher'}

# 10. WHAT ARE CONDITIONAL STATEMENTS
## 1: IF STATEMENT [do something if true]

In [264]:
age =18
if age >=18:
    print("you are an adult")

you are an adult

## 2.if else statement(do one thing or minor)

In [18]:
age =25
if age >=18:
    print("you are an adult")
else:
    print("you are minor")

you are an adult

## 3.If-elif-else statement(multiple conditions)

In [19]:
age = 18
if age >=18:
    print ("adult")
else:
    print ("minor")

adult

In [20]:
age = 15
if age >=18:
    print ("adult")
else:
    print ("minor")

minor

In [21]:
age = 30
if age >=18:
    print ("adult")
else:
    print ("minor")

adult

In [272]:
age = 25
if age >=20:
   print ('adult')
else:
  print ('minor')

adult

In [22]:
score = 85

if score >=90:
    print ("grade: A")
elif score >=80:
    print ("grade :B")
elif score >=70:
    print ("grade :C")
else :
    print("grade :F")

grade :B

In [23]:
score = 95

if score >=90:
    print ("grade: A")
elif score >=80:
    print ("grade :B")
elif score >=70:
    print ("grade :C")
else :
    print("grade :F")

grade: A

In [24]:
score = 60

if score >=90:
    print ("grade: A")
elif score >=80:
    print ("grade :B")
elif score >=70:
    print ("grade :C")
else :
    print("grade :F")

grade :F

## 11.WHAT IS A LOOPS.....

In [25]:
# for loop
for i in range (5):
    print(i)

0
1
2
3
4

In [26]:
# for loop
for i in range (3):
    print(i)

0
1
2

In [27]:
fruits=['apple','banana','cherry']
for fruit in fruits:
    print (fruit)

apple
banana
cherry

# loop through a string

In [28]:
word ="python"
for letter in word:
    print(letter)

p
y
t
h
o
n

In [29]:
word ="Victor"
for letter in word:
    print(letter)

V
i
c
t
o
r

## DATA SCIENCE EXAMPLE- loop through Dataframe

In [30]:
import pandas as pd
#create sample data
data ={
    'name' : ['Alice','Bob','Charlie'],
    'score' : [85,62,90]
}
df = pd.DataFrame(data)
# loop through rows
for index ,row in df.iterrows():
    print(f'{row['name']}) scored {row['score']}')

Alice) scored 85
Bob) scored 62
Charlie) scored 90

In [31]:
import pandas as pd
#create sample data
data ={
    'name' : ['Alice','Bob','Charlie'],
    'score' : [85,62,90]
}
df = pd.DataFrame(data)
df

      name  score
0    Alice     85
1      Bob     62
2  Charlie     90

## 12.Functions

In [32]:
def greet(name) :
    return "Hello," + name
print(greet("Victor"))

Hello,Victor

## 13.Install Necessary libraries

#!pip install pandas
#!pip install numpy
#!pip install seaborn
#!pip install matplotlib
#!pip install wordcloud
#!pip install pillow
#!pip install plotly.express

## 14.Importing libraries

In [33]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# MATHEMATICAL OPERATIONS

## 1. Basic aruthmetic operations

In [34]:
x = 10
y = 3

addition = x + y
substraction = x - y
multiplication = x * y
division = x/y
floor_division = x // y
modulus = x & y 
exponentiation = x ** y
print ( addition,substraction,multiplication,division,floor_division,modulus,exponentiation)

13 7 30 3.3333333333333335 3 2 1000

In [35]:
import math

(square_root) = math.sqrt (25)
(absolute_value) = abs (8)
(power) = pow (3, 3)
(logarithm )= math.log (10)
log_base_10 = math.log10(100)
factorial = math. factorial (5)
print (square_root,absolute_value,power,logarithm,log_base_10,factorial)

5.0 8 27 2.302585092994046 2.0 120

In [36]:
##

In [37]:
import math
num = 5.6789
rounded_value = round(num, 3)
floor_value = math.floor(num)
ceil_value = math.ceil(num)
print(rounded_value, floor_value ,ceil_value)

5.679 5 6

## WORKING WITH VECTORS IN PYTHON

In [38]:
import numpy as np
# creating a vector
vector_a = np.array([1,2,3])
vector_a

array([1, 2, 3])

In [39]:
vector_b = np.array ([4,5,6])
vector_b

array([4, 5, 6])

## Vector addition

In [40]:
vector_sum= vector_a +vector_b
vector_sum

array([5, 7, 9])

## Vector substraction

In [41]:
vector_sum= vector_a - vector_b
vector_sum

array([-3, -3, -3])

## scalar multiplication

In [42]:
scalar_multiplication = 3* vector_a
scalar_multiplication

array([3, 6, 9])

## Dot Product

In [43]:
dot_product = np.dot(vector_a , vector_b)
dot_product
print('Dot product:', dot_product)

Dot product: 32

## Magnitude of a vector

In [44]:
import numpy as np
magnitude_a = np.linalg.norm(vector_a)
magnitude_a
rounded_magnitude_value= round (magnitude_a,3)
rounded_magnitude_value
print('magnitude:',rounded_magnitude_value)

magnitude: 3.742

## Working with lists in python

In [45]:
fruits=['Apple','Banana','Cherry','Date']
fruits

['Apple', 'Banana', 'Cherry', 'Date']

In [46]:
first_fruit = fruits [0]
first_fruit

'Apple'

In [47]:
last_fruit = fruits [-1]
last_fruit

'Date'

## modifying elements

In [48]:
fruits[1] = 'Blueberry'
fruits

['Apple', 'Blueberry', 'Cherry', 'Date']

## Adding elements

In [49]:

fruits.append ('Elderberry')
fruits.insert(2, 'Coconut')

## Removing elements

In [50]:
deleted_fruit = fruits.pop (3)
fruits.remove('Date')
fruits

['Apple', 'Blueberry', 'Coconut', 'Elderberry']

## list slicing

In [51]:
subset_fruits = fruits[1:3]
subset_fruits

['Blueberry', 'Coconut']

## iterating over a list

In [52]:
for fruit in fruits:
    print(fruit)

Apple
Blueberry
Coconut
Elderberry

## Sorting a list

In [53]:
fruits.sort()
fruits

['Apple', 'Blueberry', 'Coconut', 'Elderberry']

## finding the length of a list

In [54]:
num_fruits =len(fruits)
num_fruits

4

In [55]:
print('updated fruits list:',fruits)

updated fruits list: ['Apple', 'Blueberry', 'Coconut', 'Elderberry']

In [56]:
print('deleted fruits:',deleted_fruit)

deleted fruits: Cherry

In [57]:
print('subset of fruuits:',subset_fruits)

subset of fruuits: ['Blueberry', 'Coconut']

In [58]:
print('number of fruits:',num_fruits)

number of fruits: 4

# MATRICES

## What is a matrix?

In [59]:
import numpy as np
# create two 2x2 matrices
A = np.array([[1,2],
              [3,4]])
B = np.array([[2,0],
               [1,2]])

In [60]:
# perfom operations
print('A + B = \ n' , A+B)

A + B = \ n [[3 2]
 [4 6]]

In [61]:
print ('\nA - B =\n' , A - B)

A - B =
 [[-1  2]
 [ 2  2]]

In [62]:
print('\nA X B (element-wise) = \n' , A * B)

A X B (element-wise) =
 [[2 0]
 [3 8]]

In [63]:
print ('nA X B(matrix multiplication) = \n', A @ B)

nA X B(matrix multiplication) =
 [[ 4  4]
 [10  8]]

In [64]:
print('\nTranpose of A =\n', A.T)

Tranpose of A =
 [[1 3]
 [2 4]]

## Create Data frame Using Pandas (most common)

In [4]:
import pandas as pd 
#creating a data frame

In [5]:
data = {'Name' : ['Victor','Blessy','Edwin','Vell','Allan'],
    'Age' : [20,18,19,17,21],
    'County' : [ 'embu','meru','Bomet','Nyeri','Nakuru']}
df = pd.DataFrame(data)
df

     Name  Age  County
0  Victor   20    embu
1  Blessy   18    meru
2   Edwin   19   Bomet
3    Vell   17   Nyeri
4   Allan   21  Nakuru

In [6]:
import pandas as pd
df = pd.DataFrame(data)
print(df.head())

     Name  Age  County
0  Victor   20    embu
1  Blessy   18    meru
2   Edwin   19   Bomet
3    Vell   17   Nyeri
4   Allan   21  Nakuru

## Accessing columns

In [7]:
import pandas as pd
df['County']

0      embu
1      meru
2     Bomet
3     Nyeri
4    Nakuru
Name: County, dtype: object

In [8]:
import pandas as pd
df ['Name']

0    Victor
1    Blessy
2     Edwin
3      Vell
4     Allan
Name: Name, dtype: object

## Accessing rows

In [241]:
print('\nAccessing first row:')
print(df.iloc[0])

Accessing first row:
Name      Victor
Age           20
County      embu
Name: 0, dtype: object

In [242]:
print('\nAccessing first row:')
print(df.iloc[1])

Accessing first row:
Name      Blessy
Age           18
County      meru
Name: 1, dtype: object

## Adding a new column

In [243]:
df['Salary'] = [50000,70000,30000,60000,100000]
df['occupation']=['pilot','Nurse','Teacher','Dentist','politician']
df

     Name  Age  County  Salary  occupation
0  Victor   20    embu   50000       pilot
1  Blessy   18    meru   70000       Nurse
2   Edwin   19   Bomet   30000     Teacher
3    Vell   17   Nyeri   60000     Dentist
4   Allan   21  Nakuru  100000  politician

## Filtering Data

In [244]:
print('\nFiltering rows where Age >18:')

Filtering rows where Age >18:

In [245]:
df[df['Age'] > 18]

     Name  Age  County  Salary  occupation
0  Victor   20    embu   50000       pilot
2   Edwin   19   Bomet   30000     Teacher
4   Allan   21  Nakuru  100000  politician

## Sorting Data

In [246]:
df.sort_values(by='Age', ascending=False)

     Name  Age  County  Salary  occupation
4   Allan   21  Nakuru  100000  politician
0  Victor   20    embu   50000       pilot
2   Edwin   19   Bomet   30000     Teacher
1  Blessy   18    meru   70000       Nurse
3    Vell   17   Nyeri   60000     Dentist

In [247]:
df.sort_values(by='Age', ascending=True)

     Name  Age  County  Salary  occupation
3    Vell   17   Nyeri   60000     Dentist
1  Blessy   18    meru   70000       Nurse
2   Edwin   19   Bomet   30000     Teacher
0  Victor   20    embu   50000       pilot
4   Allan   21  Nakuru  100000  politician

## Grouping Data

In [248]:
df.groupby('County')['Age'].mean()

County
Bomet     19.0
Nakuru    21.0
Nyeri     17.0
embu      20.0
meru      18.0
Name: Age, dtype: float64

## **Handling missing Data**
### Introducing a missing value

In [249]:
df.loc[2, 'Salary'] = None
df

     Name  Age  County    Salary  occupation
0  Victor   20    embu   50000.0       pilot
1  Blessy   18    meru   70000.0       Nurse
2   Edwin   19   Bomet       NaN     Teacher
3    Vell   17   Nyeri   60000.0     Dentist
4   Allan   21  Nakuru  100000.0  politician

In [250]:
print ('\nDataFrame with missing value:')
df

DataFrame with missing value:

     Name  Age  County    Salary  occupation
0  Victor   20    embu   50000.0       pilot
1  Blessy   18    meru   70000.0       Nurse
2   Edwin   19   Bomet       NaN     Teacher
3    Vell   17   Nyeri   60000.0     Dentist
4   Allan   21  Nakuru  100000.0  politician

## supress warning

In [251]:
import warnings
warnings.simplefilter('ignore')

In [252]:
print ('\nFilling missing values with mean salary:')
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
df

Filling missing values with mean salary:

     Name  Age  County    Salary  occupation
0  Victor   20    embu   50000.0       pilot
1  Blessy   18    meru   70000.0       Nurse
2   Edwin   19   Bomet   70000.0     Teacher
3    Vell   17   Nyeri   60000.0     Dentist
4   Allan   21  Nakuru  100000.0  politician

## Introducing a missing value

In [253]:
df.loc[2,'occupation'] = None
df

     Name  Age  County    Salary  occupation
0  Victor   20    embu   50000.0       pilot
1  Blessy   18    meru   70000.0       Nurse
2   Edwin   19   Bomet   70000.0        None
3    Vell   17   Nyeri   60000.0     Dentist
4   Allan   21  Nakuru  100000.0  politician

## Replace the missing value(Categorical)

In [254]:
df['occupation'].fillna(df['occupation'].mode()[0], inplace=True)
df

     Name  Age  County    Salary  occupation
0  Victor   20    embu   50000.0       pilot
1  Blessy   18    meru   70000.0       Nurse
2   Edwin   19   Bomet   70000.0     Dentist
3    Vell   17   Nyeri   60000.0     Dentist
4   Allan   21  Nakuru  100000.0  politician

# **EXERCISE**
## Create DataFrame

In [255]:
# Method 1: FROM A DICTIONARY
data={'Name':['Allan','Victor','Blessy','Vell','Edwin'],
      'Age':[20,18,19,22,30],
      'Counties':['Kiambu','Meru','Embu','Tharaka','Nairobi'],
      'Salary':[10000,20000,90000,120000,70000],
      'Universities':['Chuka','UON','KU','MKU','Embu U']}
df=pd.DataFrame(data)
print(df)

     Name  Age Counties  Salary Universities
0   Allan   20   Kiambu   10000        Chuka
1  Victor   18     Meru   20000          UON
2  Blessy   19     Embu   90000           KU
3    Vell   22  Tharaka  120000          MKU
4   Edwin   30  Nairobi   70000       Embu U

In [256]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      object
 1   Age           5 non-null      int64
 2   Counties      5 non-null      object
 3   Salary        5 non-null      int64
 4   Universities  5 non-null      object
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes